config/routes.rb
Rails.application.routes.draw do
  root "links#index"
  resources :links
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api/common.rb
class Api::Common
	# require 'net/http'
 	#  	require 'uri'
	def get_video
	    response = HTTParty.get('https://www.googleapis.com/youtube/v3/videos?part=contentDetails,statistics&id=4Y4YSpF6d6w&key=AIzaSyBeMC4eMb_u-IqGeYRSpAzED8m5RcjTumg')
	    puts "DATA - #{response["items"][0]["statistics"]["viewCount"]}"
	    @response = JSON.parse response.to_json
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
	validates :link_text, presence: true, uniqueness: { case_sensitive: false}
	# after_create :save_video_viewcount
 #  	after_update :save_video_viewcount


  	def save_video_viewcount
  		response = HTTParty.get('https://www.googleapis.com/youtube/v3/videos?part=contentDetails,statistics&id=4Y4YSpF6d6w&key=AIzaSyBeMC4eMb_u-IqGeYRSpAzED8m5RcjTumg')
  		puts "Calling save video count"
	    puts "DATA - #{response["items"][0]["statistics"]["viewCount"]}"
	    self.update.attributes(:ranking => response["items"][0]["statistics"]["viewCount"] )
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # include Httparty
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def api_common
    Api::Common.save_video_viewcount
    # return Api::Common.new
  end
  def index
    # @links = Link.all
    @links = Link.order(ranking: :desc)
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        save_video_viewcount(@link)
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        save_video_viewcount(@link)
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        save_video_viewcount(@link)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        # save_video_viewcount(@link)
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:link_text, :view_count, :videoid,:published_at)
    end

    def save_video_viewcount(link)
      id = parse_youtube(link.link_text)
      puts "id = #{id}"
      # api = "https://www.googleapis.com/youtube/v3/videos?part=contentDetails,statistics&id=#{id}&key=AIzaSyBeMC4eMb_u-IqGeYRSpAzED8m5RcjTumg"
      api = "https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&id=#{id}&key=AIzaSyBeMC4eMb_u-IqGeYRSpAzED8m5RcjTumg"
      response = HTTParty.get(api.to_s)
      link.update_attributes(:view_count => response["items"][0]["statistics"]["viewCount"],:published_at => response["items"][0]["snippet"]["publishedAt"],
        :ranking => (response["items"][0]["statistics"]["viewCount"].to_i / (Date.today - Date.parse(response["items"][0]["snippet"]["publishedAt"])).to_i ).to_f,
        :thumbnail => response["items"][0]["snippet"]["thumbnails"]["default"]["url"],
        :title => response["items"][0]["snippet"]["title"]
        )

    end

    def parse_youtube(url)
      regex = /(?:.be\/|\/watch\?v=|\/(?=p\/))([\w\/\-]+)/
      url.match(regex)[1]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YtLocal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(link) do |f| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_text %>
    <%= f.text_field :link_text ,:style => "width:35%;" %>
  </div>

  <div class="field">
    <%#= f.label :view_count %>
    <%= f.hidden_field :view_count %>
  </div>

  <div class="field">
    <%#= f.label :videoid %>
    <%= f.hidden_field :videoid %>
  </div>
  <div class="field">
    <%#= f.label :published_at %>
    <%= f.hidden_field :published_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Ranking</th>
      <th>Image</th>
      <th>Title</th>
      <th>View Count</th>
      <th>Published Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.ranking %></td>
        <td>
          <% unless link.thumbnail.blank? %>
            <%= image_tag link.thumbnail %>
          <% end %> 
        </td>
        <td><%= link.title %></td>
        <td><%= link.view_count %></td>
        <td><%= link.published_at %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ranking:</strong>
  <%= @link.ranking %>
</p>
<p>
  <strong>Thumbnail:</strong>
  <% unless @link.thumbnail.blank? %>
  	<%= image_tag @link.thumbnail %>
  <% end %>	
</p>
<p>
  <strong>Link text:</strong>
  <%= @link.link_text %>
</p>

<p>
  <strong>View Count:</strong>
  <%= @link.view_count %>
</p>

<p>
  <strong>Published At:</strong>
  <%= @link.published_at %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>